
import { Inter } from "next/font/google";
import Subnavbar from "../../components/Subnavbar";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

const links = [
    { label: "Aim", url: "/experiment7" },
    { label: "Theory", url: "/experiment7/theory" },
    { label: "Pretest", url: "/experiment7/pretest" },
    { label: "Procedure", url: "/experiment7/procedure" },
    { label: "Simulation", url: "/experiment7/simulation" },
    { label: "Posttest", url: "/experiment7/posttest" },
    { label: "References", url: "/experiment7/reference" },
    { label: "Feedback", url: "/experiment7/feedback" },
  
  ];
  
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Subnavbar links={links}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
