import { Inter } from "next/font/google";
import Subnavbar from "../../components/Subnavbar";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

const links = [
    { label: "Aim", url: "/experiment3" },
    { label: "Theory", url: "/experiment3/theory" },
    { label: "Pretest", url: "/experiment3/pretest" },
    { label: "Procedure", url: "/experiment3/procedure" },
    { label: "Simulation", url: "/experiment3/simulation" },
    { label: "Posttest", url: "/experiment3/posttest" },
    { label: "References", url: "/experiment3/reference" },
    { label: "Feedback", url: "/experiment3/feedback" },
  
  ];
  
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Subnavbar links={links}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
