import { Inter } from "next/font/google";
import Subnavbar from "../../components/Subnavbar";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

const links = [
  { label: "Aim", url: "/experiment2" },
  { label: "Theory", url: "/experiment2/theory" },
  { label: "Pretest", url: "/experiment2/pretest" },
  { label: "Procedure", url: "/experiment2/procedure" },
  { label: "Simulation", url: "/experiment2/simulation" },
  { label: "Posttest", url: "/experiment2/posttest" },
  { label: "References", url: "/experiment2/reference" },
  { label: "Feedback", url: "/experiment2/feedback" },
];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Subnavbar links={links} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
