
import { Inter } from "next/font/google";
// import Subnavbar from "../../components/Subnavbar";
// import Exps from "../../components/Exps";

import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

const links = [
    { label: "Aim", url: "/experiment4" },
    { label: "Theory", url: "/experiment4/theory" },
    { label: "Pretest", url: "/experiment4/pretest" },
    { label: "Procedure", url: "/experiment4/procedure" },
    { label: "Simulation", url: "/experiment4/simulation" },
    { label: "Posttest", url: "/experiment4/posttest" },
    { label: "References", url: "/experiment4/reference" },
    { label: "Feedback", url: "/experiment4/feedback" },
  
  ];
  
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {/* <Subnavbar links={links}/> */}
        {/* <Exps/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
